#!/bin/bash
#SBATCH --job-name=metabat2_binning
#SBATCH --output=log/metabat2_%j.out
#SBATCH --error=log/metabat2_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=56
#SBATCH --mem=256G

# --- Load Central Configuration ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../config.sh"

POLISHED_DIR="${RESULT_DIR}/final_polished"
READ_DIR="${RESULT_DIR}/k2"
BINNING_DIR="${RESULT_DIR}/binning"
BINNED_DIR="${RESULT_DIR}/binned_assemblies"

mkdir -p "$BINNING_DIR" "$BINNED_DIR" "$LOG_DIR"

echo "====================================================="
echo "        METABAT2 AUTOMATED METAGENOME BINNING        "
echo "====================================================="
echo "Input Polished Assemblies: $POLISHED_DIR"
echo "Reads Directory:           $READ_DIR"
echo "Output Directory:          $BINNING_DIR"
echo "Binned Assemblies Dir:     $BINNED_DIR"
echo "====================================================="

# Loop through samples in the samples sheet
while IFS=$'\t' read -r SAMPLE R1_PATH R2_PATH GENUS SPECIES; do
    if [[ "$SAMPLE" == "name" || -z "$SAMPLE" ]]; then
        continue
    fi

    echo "=== Processing Binning for Sample: $SAMPLE ==="

    assembly="${POLISHED_DIR}/${SAMPLE}/${SAMPLE}_final_polished.fasta"
    if [[ ! -f "$assembly" ]]; then
        echo "Warning: Polished assembly for $SAMPLE not found at $assembly. Skipping."
        continue
    fi

    WORK_DIR="${BINNING_DIR}/${SAMPLE}"
    mkdir -p "$WORK_DIR"
    
    # Define Inputs/Outputs
    fq1="${READ_DIR}/clean.${SAMPLE}_1.fq.gz"
    fq2="${READ_DIR}/clean.${SAMPLE}_2.fq.gz"
    bam_file="${WORK_DIR}/${SAMPLE}.sorted.bam"
    depth_file="${WORK_DIR}/${SAMPLE}_depth.txt"
    bin_dir="${WORK_DIR}/bins"

    # --- Step 1: Mapping (Required for Metabat2 Coverage) ---
    if [[ ! -f "$bam_file" ]]; then
        echo "--> Mapping reads to polished assembly..."
        
        # Index assembly
        pixi run -e assembly bwa index "$assembly"
        
        # Map and Sort (using CPUS_MED for mem, CPUS_MIN for sort)
        pixi run -e assembly bwa mem -t "$CPUS_MED" "$assembly" "$fq1" "$fq2" | \
            pixi run -e assembly samtools sort -@ "$CPUS_MIN" -m 4G -o "$bam_file" -
        
        pixi run -e assembly samtools index "$bam_file"
    else
        echo "--> BAM exists, skipping mapping."
    fi

    # --- Step 2: Metabat2 Binning ---
    if [[ ! -d "$bin_dir" || -z "$(ls -A "$bin_dir" 2>/dev/null)" ]]; then
        echo "--> Running Metabat2..."
        mkdir -p "$bin_dir"

        # Calculate coverage
        pixi run -e taxonomy jgi_summarize_bam_contig_depths \
            --outputDepth "$depth_file" \
            "$bam_file"

        # Run Binning
        pixi run -e taxonomy metabat2 \
            -i "$assembly" \
            -a "$depth_file" \
            -o "${bin_dir}/${SAMPLE}_bin" \
            -t "$CPUS_MED" \
            -m 1500 # Min contig size 1500bp
    else
        echo "--> Bins exist, skipping binning."
    fi

    # --- Step 3: Select the Best Bin and Copy to Binned Assemblies ---
    # Find largest bin by size
    best_bin=$(ls -S "$bin_dir"/*.fa 2>/dev/null | head -n 1)

    if [[ -n "$best_bin" ]]; then
        echo "--> Selected best bin: $best_bin"
        cp "$best_bin" "$BINNED_DIR/${SAMPLE}.fasta"
    else
        echo "WARNING: No bins generated by MetaBAT2 for $SAMPLE. Using entire polished assembly instead."
        cp "$assembly" "$BINNED_DIR/${SAMPLE}.fasta"
    fi

    echo "=== Finished Sample $SAMPLE ==="
    echo "-----------------------------------------------------"
done < "$INPUT_SHEET"

# Create success flag for pipeline resume mechanism
touch "$BINNED_DIR/metabat_success.flag"
echo "MetaBAT2 binning completed successfully!"
echo "====================================================="
